# Generated by Django 5.2.4 on 2025-07-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ManyToManyField(related_name='users', to='account.account'),
        ),
    ]
