# Generated by Django 5.2.4 on 2025-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='location_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='location_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
